// flow-typed signature: 8b3928b402e4626546d04ddc5a972032
// flow-typed version: <<STUB>>/writefile_v^0.2.8/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'writefile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'writefile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'writefile/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'writefile/index' {
  declare module.exports: $Exports<'writefile'>;
}
declare module 'writefile/index.js' {
  declare module.exports: $Exports<'writefile'>;
}
declare module 'writefile/stream.js' {
  declare module.exports: $Exports<'writefile/stream'>;
}
